in process_args_into_dataframe
    raise ValueError(err_msg)
ValueError: Value of 'names' is not the name of a column in 'data_frame'. Expected one of ['Percentage', 'proportion'] but received: Closure Code
