  File "C:\Users\AD39644\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 847, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\AD39644\\OneDrive - Lumen\\Python Version\\Clean\\29165065 - 2025-03-06 - Pre-Checks.txt' -> 'C:\\Users\\AD39644\\OneDrive - Lumen\\Python Version\\Region\\IP Mismatch\\Region/IP Mismatch 29165065 - 2025-03-06 - Pre-Checks.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\CRT IPv6 Check.py", line 121, in <module>
    main()
  File "c:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\CRT IPv6 Check.py", line 118, in main
    process_file(filepath, base_dir)
  File "c:\Users\AD39644\Desktop\EIS\OneDrive_2024-07-25\Auditing Script\CRT IPv6 Check.py", line 67, in process_file
    shutil.move(filepath, target_path)
  File "C:\Users\AD39644\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 867, in move
    copy_function(src, real_dst)
  File "C:\Users\AD39644\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
FileNotFoundError: [WinError 3] The system cannot find the path specified
